### ISSUE TITLE
NVidia backlight and MCFG table

### ISSUE THREAD

**Issue by whatnameisit** [1Revenger1/Dell-M4700-MacOS-Resources#1]
Hey, I don't have the Dell machine, but I do have a SNB laptop with NV315M. I don't know if opening an issue would be the best way to contact you, but here I go...
I use AppleBacklightFixup.kext which remains at RehabMan's github and bitbucket for working backlight control. While adding the PNLF device and the kext works OOB, smoother control experience can be achieved by changing the scope of the PNLF device to be under the GFX device. There is a discussion on using an injector kext and adding backlight objects under PNLF, but I never succeeded: https://www.insanelymac.com/forum/topic/323010-please-help-me-fix-brightness-control-nvidia-graphics-only-laptop/
It is sometimes true the SSDT generated by ssdtPRGen needs MCFG dropped to avoid boot hang, but modifying the frequency vector with CPUFriend successfully boots into the login screen without dropping MCFG, at the cost of losing AGPM...? The loss of AGPM may be due to kext attachment issues, but it seems ssdtPRGen needs some fix to work correctly. To my knowledge, OpenCore Docs never mention the need to drop MCFG. Plus, MCFG is needed for my laptop for C-states; otherwise, their initialization fails.

**Comment by averycblack** [comment]
Uhh, This is kinda hard to read tbh.

I haven't seen working backlight control on a laptop using the Nvidia GPU, so I don't know anything there.

Yes, generally when using ssdtPRGen, you need to drop the CpuPM table and maybe? MCFG. OpenCore doesn't have a lot of documentation for older systems like that, so I'm not suprised it's mentioned. CPUFriend is for Haswell+ CPUs which support using xcpm for power management (which Ivy Bridge and before do *not* support except for Ivy Bridge-E).

**Comment by whatnameisit** [comment]
I did drop OEM CpuPm. There are no apparent reasons why MCFG needs to be dropped. The instructions on CPUFriend says kext can work for both X86PlatformPlugin and ACPI_SMC_PlatformPlugin. The former is Ivy+ and the latter is for anything else.
NVidia GPU backlight works on mine with ACPIBacklightFixup and PNLF.
Anyways, thanks for reading so far :)
