### ISSUE TITLE
Dell M6700 Big Sur Install

### ISSUE THREAD

**Issue by lego1234-cloud** [1Revenger1/Dell-M4700-MacOS-Resources#2]
Hello, I have a Dell Precision M6700 with an i7-3740qm, 32gb 1600MHz ddr3 ram, Intel HD 4000 and NVIDIA K3000m quadro graphics. I have tried many OC folders in order to install or even boot into the Big Sur USB installer. I have tried beta 1, 2, and three with no success. I also did the latest version of OpenCore with no success with booting into the USB. If I can have some help, I would really appreciate that as I have tried everything to get it working

**Comment by lego1234-cloud** [comment]
[EFI OC DELL M6700.zip](https://github.com/1Revenger1/Dell-M4700-MacOS-Resources/files/4974905/EFI.OC.DELL.M6700.zip)

**Comment by averycblack** [comment]
Big Sur is a developer beta, not even a general public beta yet. In addition, a lot of kexts like Lilu still need updating - so idk why your trying so hard for Big Sur.

If this is your first time trying to install macOS, start with Catalina.

**Comment by lego1234-cloud** [comment]
This is not my first time doing a mac install for a hackintosh.
