### ISSUE TITLE
Opencore boot errors

### ISSUE THREAD

**Issue by snakus** [1Revenger1/Dell-M4700-MacOS-Resources#4]
Why getting errors [https://i.postimg.cc/pTjwJbV4/errors.jpg](https://i.postimg.cc/pTjwJbV4/errors.jpg)

**Comment by averycblack** [comment]
This config.plist is old, and OpenCore makes changes to the config.plist format as required, so quite a bit of the config plist is out of date. Update it yourself, or create a new one and add back in the device properties and other things. I have no intention of updating this repo for now as my M4700 causes me eye strain.

**Comment by snakus** [comment]
Please tell me what version of opencore was used for this configs

**Comment by averycblack** [comment]
My bad I guess for not putting in the version originally. Looks like 0.5.1 or 0.5.2, since I last updated it about ~13 months ago and they usually release a new version every month.

**Comment by snakus** [comment]
Thank You.
Do You have working EFI folder for M4700 with AMD Graphics?

**Comment by averycblack** [comment]
Not right now, was messing with some stuff on it when Big Sur initially released it's first beta and some things like backlight curves are messed up. Main thing that makes AMD graphics work are the device properties though

**Comment by snakus** [comment]
How to make it work? some tutorial? i've got AMD Radeon R9 M200X Series

**Comment by shichem420** [comment]
Hello, where can I get network cards ?

**Comment by averycblack** [comment]
If I remember correctly, I got my AzureWave CE-123h on ebay years ago way before I hackintoshed my laptop. Looks to still be relatively cheap though still.

Edit: Also, for questions like these, please open another issue rather than polluting another.
